on: push

jobs:
  job1-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensagem
        run: echo "Olá, Mundo"
  job2-gitstatus:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4

      - name: Step 2 - Marcar o diretório como seguro
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Step 3 - Git Status
        run: |
          git status

      - name: Step 4 - Imprimir mensagem
        run: echo "Tudo certo!"

  job3-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Sequencia de instruções
        run: |
          echo "Uma nova instrução"
          ls

      - name: Step 2 - Imprimir mensagem
        run: echo "Até logo!"
